--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LEDGER_BOARD
--------------------------------------------------------

  CREATE TABLE "LOLONG"."LEDGER_BOARD" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_REGIST_ID" VARCHAR2(20 BYTE), 
	"BOARD_REGIST_DATE" VARCHAR2(20 BYTE), 
	"BOARD_MODIFY_ID" VARCHAR2(20 BYTE), 
	"BOARD_MODIFY_DATE" VARCHAR2(20 BYTE), 
	"BOARD_STATUS" VARCHAR2(20 BYTE), 
	"BOARD_SOURCE" VARCHAR2(200 BYTE), 
	"BOARD_DESTINATION" VARCHAR2(200 BYTE), 
	"BOARD_MONEY_STATUS" VARCHAR2(20 BYTE), 
	"BOARD_MONEY" VARCHAR2(20 BYTE), 
	"BOARD_TAX" VARCHAR2(20 BYTE), 
	"BOARD_TEL" VARCHAR2(20 BYTE), 
	"BOARD_REGIST_YY" VARCHAR2(20 BYTE), 
	"BOARD_REGIST_MM" VARCHAR2(20 BYTE), 
	"BOARD_REGIST_DD" VARCHAR2(20 BYTE), 
	"BOARD_STATUS_COUNT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOLONG" ;
REM INSERTING into LOLONG.LEDGER_BOARD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LEDGERBOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LEDGERBOARD_PK" ON "SYSTEM"."LEDGER_BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LEDGER_BOARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LEDGER_BOARD" ADD CONSTRAINT "LEDGERBOARD_PK" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."LEDGER_BOARD" MODIFY ("BOARD_NO" NOT NULL ENABLE);

  
--------------------------------------------------------
--  SEQUENCE
--------------------------------------------------------
  CREATE SEQUENCE SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOMINVALUE;