package com.dev.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "employee")
public class Employee {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String employeeId;
	
	@DynamoDBAttribute
	private String company;
	
	@DynamoDBAttribute
	private String employeeName;
	
	
	@DynamoDBAttribute
	private String etc;
	
	@DynamoDBAttribute
	private String yn;
	
	/*
	@DynamoDBAttribute
	private String firstName;
	
	@DynamoDBAttribute
	private String lastName;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private Department department;
	*/
	
}
