package com.dev.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "gamedata")
public class GameData {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String releaseData;
	
	@DynamoDBAttribute
	private String no;
	
	@DynamoDBAttribute
	private String genere;
	
	@DynamoDBAttribute
	private String platform;
	
	@DynamoDBAttribute
	private String price;
	
	@DynamoDBAttribute
	private String producer;
	
	@DynamoDBAttribute
	private String publishing;
	
	@DynamoDBAttribute
	private String title;
	
	@DynamoDBAttribute
	private String yn;
	/*
	@DynamoDBAttribute
	private String firstName;
	
	@DynamoDBAttribute
	private String lastName;
	
	@DynamoDBAttribute
	private String email;
	
	@DynamoDBAttribute
	private Department department;
	*/
	
}
